# Generated by Django 2.1.7 on 2019-03-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=40)),
                ('Username', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
                ('DOB', models.CharField(max_length=40)),
                ('City', models.CharField(max_length=40)),
                ('State', models.CharField(max_length=40)),
            ],
        ),
    ]
