# Generated by Django 2.1.7 on 2019-03-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clever', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=40)),
                ('Submit', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.CharField(max_length=40)),
                ('Answers', models.CharField(max_length=40)),
            ],
        ),
    ]
