# Generated by Django 2.1.7 on 2019-03-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clever', '0002_login_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.CharField(max_length=40)),
                ('Answers', models.CharField(max_length=40)),
            ],
        ),
    ]
